### PR TITLE
upgrade credo dep from 1.0.5 to 1.4.0

### PR DESCRIPTION
**Pull request by adrianomitre**
Depends on https://github.com/adrianomitre/async_with/pull/1.

### CODE REVIEW

**Comment by fertapric** [comment]
I squashed the commits on #68, could you adapt this PR to the new `master`? 🙏 Thanks!

**Comment by adrianomitre** [comment]
The CI part is done, but the code needs some adjustments to conform to credo 1.4.0 standards:

image

Given the code that needs to be changed relies heavily on macros and my first attempts unfortunately did not work, I would be glad if you could offer some guidance here, @fertapric.

**Comment by fertapric** [comment]
@adrianomitre Oh! I’ll take a look then next week, fix the offenses, and then merge this PR (I’m currently on vacation). Thanks for looking into this!

**Comment by fertapric** [comment]
Hi @adrianomitre! I've decided to remove Credo altogether. Thanks for the PR! 💜

**Comment by adrianomitre** [comment]
> Hi @adrianomitre! I've decided to remove Credo altogether. Thanks for the PR! 💜 

@fertapric Would you mind explaining why?

**Pull request closed without merging**
